### ISSUE TITLE
MonkeyCache.2.0.0-beta downgrading Newtonsoft.Json

### ISSUE THREAD

**Issue by Orgbrat** [jamesmontemagno/monkey-cache#110]
Was going to upgrade MonkeyCache.1.6.2 to 2.0.0-beta but I  stopped when I noticed that it was downgrading Newtonsoft.13.0.1 to 12.0.3. Is this correct?

**Comment by jamesmontemagno** [comment]
Yes, you should not use 2.0.0-beta is it replacing Newtonsoft with system.text.json and only supports .net 6

**Comment by jamesmontemagno** [comment]
It probably is because a different package you are using relies on 12.0.3
