### ISSUE TITLE
Possible Issue on the AppStore

### ISSUE THREAD

**Issue by fdhsdrdark** [jamesmontemagno/monkey-cache#132]
Hey,

Thank you very much for supporting this package and providing an updated version,
supporting migration from traditional Xamarin to .Net 6/7.

I run into an issue though on my updated .Net iOS app and I'm not really sure if this package is related in any way.

When I uploaded my app on the App Store I got an email about the app being rejected, with the following
"The app references non-public symbols in MyAppName: _ubrk_openRules, _ucal_add, _ucal_close, _ucal_get, _ucal_getAttribute, _ucal_getKeywordValuesForLocale, _ucal_getNow, _ucal_getTimeZoneDisplayName, _ucal_getTimeZoneIDForWindowsID, _ucal_getWindowsTimeZoneID....".

Searching about the error got down to the symbols above being related to libicucore, a native library providing 
Unicode and localization support (I was not able to figure that out by myself - got it from a response on an issue I raised for another possible offended package). 

I am trying to find the offended package on my project by checking the ones updated from the migration. MonkeyCache.FileStore is one of the few updated ones.

Is there any change the error is coming from the updated Monkey.Cache package?

Thanks vey much for any response.

**Comment by jamesmontemagno** [comment]
Hmmmm I don't think so. We do use the DateTime, but it is UTC time...  I have apps with this library in the app store and that code hasn't really changed at all.

I feel like it is something around the first symbol _ubrk_openRules usually is the issue, but I have never seen this.

Linking: https://github.com/dotnet/runtime/issues/86156

**Comment by fdhsdrdark** [comment]
@jamesmontemagno Thanks very much for getting back on this - spotted the offended package by removing one by one the  packages from the project and submitting consecutively on the AppStore. 
Just mentioning it here if anyone comes across a similar issue.
