### ISSUE TITLE
Installation MonkeyCache.FileStore faillure

### ISSUE THREAD

**Issue by tobus2012** [jamesmontemagno/monkey-cache#135]
Hello when I try to install MonkeyCache.FileStore on my xamarin.Forms project version 5.0.0.2515 I have a version problem.

I don't know what the problem is

![monkeyCache](https://github.com/jamesmontemagno/monkey-cache/assets/5566744/93406baf-53be-4227-b9d7-03ddf9dcfffc)

**Comment by jamesmontemagno** [comment]
Correct, version 2.0 is not compatible with Xamarin anymore, you can use v 1.x until you upgrade.

**Comment by jamesmontemagno** [comment]
updated readme
