### ISSUE TITLE
Question:  Can expiration days  be null?

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/monkey-cache#17]
As I review the code I can use it to store data even not from http. For example I am using akavache as to store user results. If user plays a game, I create object with akavache and using "Save" I save it and "Get" to display results. Therefore those in app data never gets expired. Is it possible to that? Akavache exposes this parameter as nullable.

**Comment by EmilAlipiev** [comment]
Ok, actually you  described clearly that it is in our hand to handle network, expiration and reretrieve cases. I was confused because i jumped to code first :) I still believe if parameter days could be nullable for the users who dont want their data to be never expired even though we can handle it ourselves, just to remove confusion :)

**Comment by jamesmontemagno** [comment]
Yeah, I mean you could just set it to 1000 years in the future too as an option.
