### ISSUE TITLE
GetAll and EmptyAll for same type?

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/monkey-cache#18]
For some cases it could be useful to cache same object type (serialized into string) with different keys but under same group. Could be possible to extend Banana with some kind of "groupkey" and have function like IEnumerable<T>GetAll<T>(string Groupkey); and EmptyAll for a group. Just an idea. it can be useful.

**Comment by jamesmontemagno** [comment]
I actually only get and retrieve by the ID and not the type, so I can't really query for a type at all.
