### ISSUE TITLE
How is it different than SettingsPlugin?

### ISSUE THREAD

**Issue by Im-PJ** [jamesmontemagno/monkey-cache#19]
Reading the docs, I know both the plugins save data at different locations but I'm trying to understand why and how these two plugins will be used inside same app. Sorry for asking a question here.

**Comment by jamesmontemagno** [comment]
Great question. I would also first say to read through this: https://github.com/jamesmontemagno/SettingsPlugin#settings-plugin-or-xamarinforms-appproperties as it will compare it to app.properties.

So with the Settings Plugin it is storing properties to the users local preferences/settings api of each platform. This is great for simple data (bool, int, and small strings). Each platform has different limitations when it comes to these different types of data and strings especially should never house a large amount of data. In fact if you try to store a super huge string on Android you could easily get an exception.

MonkeyCache enables you to easily story any type of data or just a simple string that you can easily serialize and deserialize back and forth. The key here is that you can set an expiration data associated with that data. So you can say this data should be used for the next few days. A key here is the ETag that is extra data that can be used to help with http caching and is used in the http caching library.

On top of that it integrates into your existing nugets you may already use such as sqlite or litedb, or none like the file store.

**Comment by chrisgate** [comment]
@jamesmontemagno sorry to ask this............how is this different from Akavache.

Thanks in anticipations

**Comment by EmilAlipiev** [comment]
@chrisgate James already explained in his post over twitter that it is more light weight and removing all rx packages. it has one simple task to cache your http data. Akavache does more complex things. According to my experience, Akavache is awesome library but as he said, it is really heavy for simple apps. Just check the code of monkey cache, you will see that so simple that any junior developer can understand but you need to study to understand what akavache is doing

**Comment by jamesmontemagno** [comment]
Also added stuff to readme

**Comment by EmilAlipiev** [comment]
I think that you can link to your mergeconflict talk on this topic :D  you explain there in details
