### ISSUE TITLE
Need a NuGet Icon

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/monkey-cache#2]

**Comment by timheuer** [comment]
You're welcome 
![monkeycache-logo](https://user-images.githubusercontent.com/4821/33744579-c0d31850-db66-11e7-8075-b1f7474d67f1.png)

**Comment by jamesmontemagno** [comment]
I should mention it has have proper licenses for it :)

**Comment by timheuer** [comment]
Well it didn’t seem to bother Garmin ;-)

**Comment by TonyHenrique** [comment]
![icon](https://user-images.githubusercontent.com/6307623/33767142-3a1d7348-dbff-11e7-8790-eb9c744c89e7.png)
[inkscape-icon.zip](https://github.com/jamesmontemagno/monkey-cache/files/1542701/inkscape-icon.zip)

**Comment by sthewissen** [comment]
![monkeycache](https://user-images.githubusercontent.com/2419439/33800220-006bc134-dd3c-11e7-95ba-ad6b7fcf7928.png)

[monkeycache.psd.zip](https://github.com/jamesmontemagno/monkey-cache/files/1545184/monkeycache.psd.zip)

**Comment by jamesmontemagno** [comment]
Integrate into nuget now!! <3
