### ISSUE TITLE
How to include monkeycache.db into Android AutoBackup?

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/monkey-cache#28]
If I want to backup monkeycache sqlite, 

is it enough to have   `<include domain="database" path="MoneyCache.db"/>` in my keep.xml file for android auto backup? have you ever tested it? :)

**Comment by jamesmontemagno** [comment]
Monkey Cache is a cache and can be removed at any time for any reason. It is not meant to be backed up at all. It is stored in the CacheDir: https://developer.android.com/reference/android/content/Context.html#getCacheDir()
