### ISSUE TITLE
DelegatingHandler

### ISSUE THREAD

**Issue by aloisdeniel** [jamesmontemagno/monkey-cache#3]
Maybe having a custom `DelegatingHandler` that would manage http cache could be a better solution since it would be queue-able with other `HttpHandlers` instead of having implementation hidden behind `HttpCache`(which could stay and use the custom handler).

**Comment by jamesmontemagno** [comment]
Not a bad idea, I wanted to also create another method that took in a lot more parameters for things like username/password and such. DelegatingHandler may be better. Wanna PR me?

**Comment by aloisdeniel** [comment]
Working on it! :)

**Comment by aloisdeniel** [comment]
You can take a look on my fork : https://github.com/aloisdeniel/monkey-cache 

Unfortunately, I can't test unit tests since it is based on MSTest and I'm on macOS (*and I had to remove UWP elements from csproj in order to build the project*).

**Comment by jamesmontemagno** [comment]
hmmmm. MSTest will work inside of VS for Mac... what version do you have? We added support in latest Stable. (I created it in VS for Mac) :)

**Comment by jamesmontemagno** [comment]
I ended up doing multi-targeting last night in VS 2017... haven't tried that in VS for Mac yet... :(

**Comment by aloisdeniel** [comment]
My bad, didn't know but MSTest seems okay now!

![image](https://user-images.githubusercontent.com/7687231/33961435-5b477854-e04e-11e7-9174-faf29357b183.png)

**Comment by aloisdeniel** [comment]
#4

**Comment by jamesmontemagno** [comment]
Closing for now as we have re-thought the entire thing. Now just an extension of HttpClient :)
