### ISSUE TITLE
Using TimeSpan.MaxValue in expiration makes Barrel throw Exception

### ISSUE THREAD

**Issue by melwil** [jamesmontemagno/monkey-cache#30]
Code needed to reproduce:

```cs
Barrel.Current.Add("key", "val", TimeSpan.MaxValue);
```

Expected outcome:

> Message: System.ArgumentOutOfRangeException : The added or subtracted value results in an un-representable DateTime.
> Parameter name: value

StackTrace:

> Result StackTrace:	
>at System.DateTime.AddTicks(Int64 value)
>   at MonkeyCache.FileStore.Barrel.Add(String key, String data, TimeSpan expireIn, String eTag)
>   at MonkeyCache.FileStore.Barrel.Add[T](String key, T data, TimeSpan expireIn, String eTag)

**Comment by jamesmontemagno** [comment]
Fixed in next rev

**Comment by AuriR** [comment]
This appears to be back again :-P

**Comment by AuriR** [comment]
Had same issue using .NET 6 / MAUI app. Reach out if you want to see code.
