### ISSUE TITLE
iOS cache gets cleared

### ISSUE THREAD

**Issue by FrancoisM** [jamesmontemagno/monkey-cache#31]
I use MonkeyCache to store my user info, including a jwt token.
When I start the app, I check for the existence of that cache. If it exists, the user is logged on and can query my backend. If it doesn't exist, the app starts with the login page.

All good. Except that on my iPhone, I am "disconnected" after I open the app if I haven't used a while (overnight for example). The cache is cleared. It doesn't happen on the emulator: I'm always connected day after day. It's not an expiration issue (the expiration time is 30 days). And it's hard to debug as I can't reproduce it in debug mode. 

Any know issue about iOS claiming the cache? Can we "register" to such events? Any ideas on how I can pinpoint what's happening?
Tks.

**Comment by jamesmontemagno** [comment]
This is correct... it is a cache. You would want to use settings plugin or examarin essentials api for preferences https://docs.microsoft.com/en-us/xamarin/essentials/preferences?context=xamarin%2Fxamarin-forms&tabs=android.

It is a cache and any of the operating systems can clear it at any time. This is the idea.

**Comment by FrancoisM** [comment]
Well of course it can get cleared. My point that this is cleared too fast. My iPhone has space so there are no reasons for iOS to reclaim the cache. If it is so easily cleared what 's the point of setting expiry timespan?
Anyway I'll try to get some docs on how iOS claim back the cache to pinpoint what's going on then.
Tks.

**Comment by jamesmontemagno** [comment]
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html I store in the Caches directory.

**Comment by Im-PJ** [comment]
This is also the case with Android which means I can't use it to store session tokens. cache gets cleared within a day even before session expires.

**Comment by jamesmontemagno** [comment]
You should not be using it to store session tokens you want to do that with preferences or secure storage from Xamarin.Essentials.
