### ISSUE TITLE
Failed to add Reference

### ISSUE THREAD

**Issue by johnfurog** [jamesmontemagno/monkey-cache#33]
I am getting this error when installing to my android project : 

`Failed to add reference. The package 'MonkeyCache' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component.	`

Target Framework : .Net Standard 2.0 ( converted from PCL)
Xamarin.Forms version : 2.5.0.280555
Android Target Framework Version : 8.0

**Comment by jamesmontemagno** [comment]
try 0.1.0.10-beta
