### ISSUE TITLE
Provide a way to specify where the cache is stored

### ISSUE THREAD

**Issue by harindaka** [jamesmontemagno/monkey-cache#34]
This is a feature request.

The platform specific cache directory is used to store the cache now. I guess the underlying cache provider implementation decides ultimately where the cache is created. However it would be better to provide the developers with an option to specify the cache storage location so that for example in iOS and Android, the app dir can be used.

**Comment by jamesmontemagno** [comment]
It is stored in the cache dir: https://github.com/jamesmontemagno/monkey-cache/blob/master/src/MonkeyCache/Utils.cs#L20

**Comment by jamesmontemagno** [comment]
Going to implement this today!
