### ISSUE TITLE
Expose mechanism to control JSON serialization

### ISSUE THREAD

**Issue by KevM** [jamesmontemagno/monkey-cache#35]
I've had to wrap my usage of MonkeyCache with a facade will let's me do `Get<T>` and `InsertObject<T>` where I control how the object is de|serialized. Why? I have a couple of custom converters in play that are not easily "put on the types" via `[JsonConverter]` attributes.

Exposing the `JsonSettings` object in use would be helpful. I'd be happy to create a PR if you like.

**Comment by jamesmontemagno** [comment]
sure, send the pr :)
