### ISSUE TITLE
Issue set and retrieve expiration

### ISSUE THREAD

**Issue by GrexyLoco** [jamesmontemagno/monkey-cache#37]
Hi James and Crew!

I currently tried out monkey cache simply for... well caching data and it worked great out of the box. Now i tried to implement expiration logic, but for some reason it is not working like expected. 

```DateTime? after;
    string res;
    TimeSpan ts;
    switch (timeSpanType)
    {
        case TimeSpanTypeEnums.FromMinutes:
        ts = TimeSpan.FromMinutes(validFor);
        Barrel.Current.Add(key:url.ToString(), data:result, expireIn: ts);
        after = Barrel.Current.GetExpiration(url.ToString());
        break;
        [...]
    }
```

In the added code it appears that after running into the correct case, 'ts' gets set correctly, by for example 5 minutes (validFor), then the data gets cached with the Add-method, but when I try to get the remaining expiration after adding the monkeys into the barrel, 'after' always returns "{01.01.0001 00:00:00}" BUT: IsExpired works as expected. What am I doing wrong? I bet I miss something very basic, I am not sure if this is the right place for this question. Thank you!

Best regards

Grexy

**Comment by jamesmontemagno** [comment]
Which package are you working with? File/Sqlite/Litedb

Sounds like there is a bug with "GetExpiration" not returning the correct data. Is that correct?

**Comment by GrexyLoco** [comment]
I am using Sqlite. Yes, it seems not to return the correct data.

**Comment by jamesmontemagno** [comment]
gotcha, i will take a look

**Comment by GrexyLoco** [comment]
Nice, thank you! Tell me if I can provide any further information!

**Comment by jamesmontemagno** [comment]
What platform are you working with? iOS/Android?

**Comment by GrexyLoco** [comment]
Great, thank you! Corrupt query?

**Comment by jamesmontemagno** [comment]
my select statement was incorrect :)
pushing out a 1.0-beta later today :)

**Comment by GrexyLoco** [comment]
Awsome! By the way: I am new to Xamarin and try to get used to it by private motivation. This is the reason why i stumbled over the Xamarin Show and... this shit is really great for getting a clue how to survive my private xamarin/Azure-skilling-project, nice show! Thank you for fixing. Keep on rollin'!
