### ISSUE TITLE
System.MissingMethodException: void SQLite.SQLiteConnection..ctor(string,bool)

### ISSUE THREAD

**Issue by MattiaDurli** [jamesmontemagno/monkey-cache#38]
Hello!
I'm trying monkeycache  0.1.0.10-beta in a sample app where I'm using sqlite-net-pcl 1.5.231 too.
```
Barrel.ApplicationId = "TestAppNSPrism7";            
var data = Barrel.Current.Get("test");
```
on the second line I'm getting a:
System.MissingMethodException: void SQLite.SQLiteConnection..ctor(string,bool)

Any hint on what am I doing wrong?
Thanks!

**Comment by MattiaDurli** [comment]
thanks, so should I wait an upgrade of 0.1.0.10-beta or check myget?

**Comment by jamesmontemagno** [comment]
I would rely on the current dependency of 1.4.X

I plan on finishing up a new 1.0-beta tomorrow :)

**Comment by MattiaDurli** [comment]
Works perfectly thanks!
