### ISSUE TITLE
Add Auto Expiration

### ISSUE THREAD

**Issue by dansiegel** [jamesmontemagno/monkey-cache#40]
# Description

While I certainly understand that some developers may prefer to handle removing expired values, I would suggest adding a setting that will tell MonkeyCache to automatically purge expired values.

```cs
Barrel.AutoExpire = true;

// Now returns a null if the object is expired.
var monkey = Barrel.Current.Get<Monkey>("foo");
```

**Comment by jamesmontemagno** [comment]
Hmmmmm interesting
