### ISSUE TITLE
Performance chart

### ISSUE THREAD

**Issue by nhwilly** [jamesmontemagno/monkey-cache#41]
Cool library!

I was trying to interpret the performance chart, but I can't figure out the labels. I presume the columns are milliseconds?

And the ETag values are all zero because that's not supported?

And I'm not sure exactly why there are two different charts.  I see 1-4000 for each backing store, but then what is the significance of the chart on the right? 

Sorry to be dense.

**Comment by jamesmontemagno** [comment]
* Everything is milliseconds
* 0 means it is instant return and not measurable
* The first table is 1,10,100,1000,4000 records for reach. The second table is just 1 and 1000

To be honest the perf between all of them is no big deal and just choose the dependency you want. If you already use SQLite use SQLite, if you use LiteDB use LiteDB, else just use FileStore.

**Comment by nhwilly** [comment]
I was trying akavache, but struggling and thought this was way cool. Just wanted to be sure about performance before I jumped in. Thanks for this and all the cool stuff you do.

**Comment by jamesmontemagno** [comment]
Yeah, i mean it is really just a super light weight cache system, not meant really for a database. I am changing some items around for the next beta so you can set a default directory that isn't the cache directory though.

**Comment by jamesmontemagno** [comment]
Awesome!

Shoot me an email would love to setup some time to chat about what you are working on: motz@microsoft.com
