### ISSUE TITLE
Using this with LinqPad

### ISSUE THREAD

**Issue by nhwilly** [jamesmontemagno/monkey-cache#43]
First, this is a really great library.  I  know that sounds stupid, but it *just works* and that's so refreshing.

In case this helps anyone else, I was trying to use this with LINQPad and if you create a class using the `C# Program Language` your type name becomes something useful to LINQPad but not JSON so much and it gets upset.

I feel sure there's a way to do it, but I ended up creating classes and namespaces outside the LINQPad environment and used [SWApi](https://swapi.co/) to test.  HTH.

So much fun.

**Comment by jamesmontemagno** [comment]
Not really sure? I don't have any experience. If it doesn't work you could send a PR to make it work.
