### ISSUE TITLE
Request: Barrel.Current.EmptyAllExcept(string[] keys)

### ISSUE THREAD

**Issue by JMan7777** [jamesmontemagno/monkey-cache#44]
I really love this cache and would like to issue a feature request.
I use the cache all over my app with a lot of keys but when I do some major release upgrade I would like to empty the cache for all except few keys,
Since my keys are partially dynamic it is really difficult to delete all keys except few ones which need to stay.

So it would be helpful to have some kind of exclude functionality.

    Barrel.Current.EmptyAllExcept(string[] keys);

If this is not possible please kindly provide functionality to get all the keys in the cache.
With this I could empty the keys one-by-one and exclude some keys-manually.

Thx a lot.

**Comment by jamesmontemagno** [comment]
I think here you can now do something like "GetKeys" and then remove your keys from that list. This will accomplish what you need.
