### ISSUE TITLE
Creating new HttpClient for each call

### ISSUE THREAD

**Issue by nhwilly** [jamesmontemagno/monkey-cache#45]
I know a while back it was suggested that we not create a new `HttpClient` for each call as it was thread safe and expensive.

Has that advice changed?  Or maybe it was just for `Asp.Net`.  Or `.Net` before `.Net Core`

Is it performant enough for a XF app?

TIA

**Comment by jamesmontemagno** [comment]
Under the hood it doesn't actually matter from talking with Miguel. But I should probably cache it :)

**Comment by nhwilly** [comment]
I'm pretty much a complete noob, which is why I ask the obvious questions.

My Etag documents will be coming from cosmosdb, so I'm issuing read only permission tokens directly to the mobile device. Hoping to integrate that with monkey cache.

I am facing a similar issue with DocumentClient because if you are using resource tokens, you have to create a new client instance for each token. It's only a few milliseconds, but you know how they can add up.
