### ISSUE TITLE
How to create a new DB (barrel) ?

### ISSUE THREAD

**Issue by aimore** [jamesmontemagno/monkey-cache#51]
I was wondering since we have the `Barrel.ApplicationId` the same will be used to generate multiple DBs/Barrels ?

**Comment by jamesmontemagno** [comment]
One database is all it creates and caches it around. There is no need for another database since your keys are unique entries. 

Changing the ApplicationId after you use the barrel has no effect at all since it is cached around throughout the lifespan.
