### ISSUE TITLE
file is not a database

### ISSUE THREAD

**Issue by johnmarquez13** [jamesmontemagno/monkey-cache#53]
hello, I have a problem with MonkeyCache.SqlLite 1.2.0 and I use an android api 26

I try to use this code

Barrel.ApplicationId = "Cache";
                Barrel.Current.EmptyExpired ();
                string cache = Barrel.Current.Get <string> ("Visits-" + id_bn);

and an Exception is thrown: "file is not a database"

Could you help me?

**Comment by jamesmontemagno** [comment]
do you have an example project you can share?

**Comment by jamesmontemagno** [comment]
I am unable to reproduce this at all here.
