### ISSUE TITLE
Support for custom Barrel names

### ISSUE THREAD

**Issue by jochembroekhoff** [jamesmontemagno/monkey-cache#54]
It would be great if there could be an option to create Barrel instances that have a custom name.
I know that you can specify a custom cache directory, but that isn't really convenient if you just want to create a new Barrel in the default cache directory.
Currently the default cache directory for a Barrel is `<cache dir>/<application id>/MonkeyCache`. I'd suggest having a static method like `Barrel.ForName(string barrelName)` that would still use the default cache directory, but append `barrelName` to is. So, for example if you were to call `Barrel.ForName("myBarrel")`, the Barrel would be initialised in the directory  `<cache dir>/<application id>/MonkeyCache/<barrel name>` or `<cache dir>/<application id>/MonkeyCache-<barrel name>`. Escaping may be necessary if the given custom Barrel name contains invalid path characters.

**Comment by jochembroekhoff** [comment]
Something that just came to mind is that, when using custom Barrel names, it would be useful if there would also be a method to purge all Barrels.
There is `Barrel.Current.EmptyAll()`, but it would be nice if there could also be a comparable method that would also empty all custom barrels.

**Comment by jamesmontemagno** [comment]
Thanks for the recommendation, but not looking to change it as you could just append a different name to the front.
