### ISSUE TITLE
Maximum Cache Size Limit

### ISSUE THREAD

**Issue by joshuatantonflynn** [jamesmontemagno/monkey-cache#55]
MonkeyCache is awesome, loving it so far. Was wondering if this would be useful. Have a set maximum cache limit (in bytes). So that if you cache something that goes over the limit it will first remove all expired items, but then if necessary remove the least recent items until the volume of cache hits the maximum cache limit.

I have a requirement to implement this now with an app using monkey cache. Any recommendation on how to do this? Sorry if this isn't the most appropriate place to put this.

**Comment by jamesmontemagno** [comment]
It would depend on what system you were using and try to calculate the size on disk. This data is so tiny that I highly doubt this needs to be done at all. Feel free to fork and create your own version of it, but I don't think it should be included in the default here.

**Comment by joshuatantonflynn** [comment]
Hi James, 

Right now we are caching images and even some videos. I give all my caches 7 day expiry times and clear the expired items every time something is stored/retrieved from the cache (SQLite). I guess I'm asking how do I access the SQLite database without using MonkeyCache (I suppose this is how I would have to count the size and get the list of all keys). I also understand how this is outside the scope of support, you are right to close the issue and keep it closed, but if you have any pointers it would be greatly appreciated.

Thanks,

**Comment by jamesmontemagno** [comment]
So, it is just a file on disk for SQlite/LiteDB, you could probably query that and check its size in general. Interesting use case!

**Comment by joshuatantonflynn** [comment]
Ya so I figured I could do that. But usually when using SQLite you create a DB first with a path. I was assuming monkey cache did this itself using a path starting with System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal). At least this is how I was creating my DB before I found monkeyCache 

  ```
void OpenDB()
        {
            if(!SQLSingleton.Instance.Open)
            {
                string path = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal);
                path = Path.Combine(path, "username_filename.db3");
                SQLSingleton.Instance.DB = new SQLiteConnection(path);
                SQLSingleton.Instance.Open = true;
            }
        }
```

Would I need the path to access the SQLite database used by MonkeyCache? (the singleton is just used so I can access the connection from anywhere and the open property is so I can ensure it was connected.) Or does it store the DB some other way? I suppose MonkeyCache doesn't have a way to set a specific path for the DB.

**Comment by jamesmontemagno** [comment]
Each OS is a bit different, but this does it: https://github.com/jamesmontemagno/monkey-cache/blob/master/src/MonkeyCache/BarrelUtils.cs#L50

I grab the path correct for each platform and combine it: https://github.com/jamesmontemagno/monkey-cache/blob/master/src/MonkeyCache.SQLite/Barrel.cs#L39

**Comment by joshuatantonflynn** [comment]
Awesome. Thanks for the help. I should have checked the source myself, sorry about that. Hopefully I can do what I'm trying to do with this.

Thanks,

**Comment by jamesmontemagno** [comment]
Let me know how it goes and if you figure out something, we could always think about introducing something or some helper

**Comment by joshuatantonflynn** [comment]
So I've made this static class. It seems to do what I need:

```
public static void TrimCache(int maxSize)
        {
            MonkeyScopeSystemRequests.CheckAppId();
            Barrel.Current.EmptyExpired();

            string basePath = Path.Combine(Application.Context.CacheDir.AbsolutePath, Barrel.ApplicationId);
            string directory = Path.Combine(basePath, "MonkeyCache");
            if(Directory.Exists(directory))
            {
                string path = Path.Combine(directory, "Barrel.db");

                SQLiteConnection db = new SQLiteConnection(path);
                var cachedEntries = db.Table<Banana>().ToArray();
                cachedEntries = cachedEntries.OrderBy(_ => _.ExpirationDate.Ticks).ToArray(); 

                int totalSize = 0;
                for(int i = 0; i < cachedEntries.Length; i++)
                {
                    int sizeOfEntry = System.Text.ASCIIEncoding.Unicode.GetByteCount(cachedEntries[i].Contents);
                    totalSize += sizeOfEntry;
                }
                if(totalSize > maxSize)
                {
                    int requiredSizeToDelete = totalSize - maxSize;
                    for(int i = 0; i < cachedEntries.Length; i++)
                    {
                        int sizeOfEntry = System.Text.ASCIIEncoding.Unicode.GetByteCount(cachedEntries[i].Contents);
                        requiredSizeToDelete -= sizeOfEntry;
                        Barrel.Current.Empty(cachedEntries[i].Id);
                        if (requiredSizeToDelete <= 0)
                            break;
                    }
                }
            }
        }
```

Possible Improvements: If you know a more efficient way of getting the total size of the table the first loop is unnecessary. The orderby wasn't working for me on one line. I first had to get it as an array first. Also this appears to be redundant, as the db.Table() query already delivers it to me in this order. However, my tests were not large enough in scope for me to know 100% that this will always be the case. You'll also notice this uses the Android basepath. If you wanted to integrate this into the Barrel object it would be pretty simple to modify it accordingly. The user could just call Barrel.Current.TrimCache(maxSize); 

Thanks for the help James!
