### ISSUE TITLE
Would a sqllite-net encryption provider be useful.

### ISSUE THREAD

**Issue by clawrenceks** [jamesmontemagno/monkey-cache#57]
I am aware that there are two database backed providers for MonkeyCache, SQLite and LiteDB. As I understand it the only provider that offers encryption is the LiteDB provider. It would appear that there are however security concerns with the encryption implementation in LiteDB (open issue at https://github.com/mbdavid/LiteDB/issues/581).

A SQLite provider exists, which doesn't provide an encryption option. I believe that SQLite-net does provide encryption (via the sqlite-net-sqlcipher package) and I that got me wondering a couple of things.

1) Would a SQLite-net provide for Monkey Cache that supports encryption be something useful? I imagine it wouldn't be too different from the SQLite provider? Or is there some other reason that a SQLite-net provider is not viable?

2) Is it possible for a user of Monkey Cache to provide their own persistence provider, rather than using one of the existing providers?

**Comment by jamesmontemagno** [comment]
You should consider cloning the code and integrating: https://github.com/praeclarum/sqlite-net#using-sqlcipher
