### ISSUE TITLE
Read-only issue while executing MonkeyCache.SQLite.Barrel.Empty

### ISSUE THREAD

**Issue by sykrishna** [jamesmontemagno/monkey-cache#58]
Hi James,

I am facing the below issue while executing 
MonkeyCache.SQLite.Barrel.Empty().

Error log:
04-02 22:32:07.346 16465 16465 E AndroidRuntime: android.runtime.JavaProxyThrowable: SQLite.SQLiteException: ReadOnly
04-02 22:32:07.346 16465 16465 E AndroidRuntime:   at SQLite.SQLiteCommand.ExecuteNonQuery () [0x000c0] in <e6176266e10e4143a13a15e20e5b743c>:0 
04-02 22:32:07.346 16465 16465 E AndroidRuntime:   at SQLite.SQLiteConnection.Execute (System.String query, System.Object[] args) [0x0003a] in <e6176266e10e4143a13a15e20e5b743c>:0 
04-02 22:32:07.346 16465 16465 E AndroidRuntime:   at SQLite.SQLiteConnection.Delete (System.Object primaryKey, SQLite.TableMapping map) [0x00048] in <e6176266e10e4143a13a15e20e5b743c>:0 
04-02 22:32:07.346 16465 16465 E AndroidRuntime:   at SQLite.SQLiteConnection.Delete[T] (System.Object primaryKey) [0x00013] in <e6176266e10e4143a13a15e20e5b743c>:0 
04-02 22:32:07.346 16465 16465 E AndroidRuntime:   at MonkeyCache.SQLite.Barrel+<>c__DisplayClass22_0.<Empty>b__0 () [0x0000f] in <407b98dd74624081a17e95bdc70a6233>:0 
04-02 22:32:07.346 16465 16465 E AndroidRuntime:   at SQLite.SQLiteConnection.RunInTransaction (System.Action action) [0x0001d] in <e6176266e10e4143a13a15e20e5b743c>:0 
04-02 22:32:07.346 16465 16465 E AndroidRuntime:   at MonkeyCache.SQLite.Barrel.Empty (System.String[] key) [0x00025] in <407b98dd74624081a17e95bdc70a6233>:0 

Any suggestions ?

**Comment by jamesmontemagno** [comment]
Hmmmm What version of SQLite-net do you have? @praeclarum have you seen this ever?

**Comment by sykrishna** [comment]
1.4.118

**Comment by sykrishna** [comment]
Hi james,

I have couple of other findings related to this issue. 

1. Issue occurs when we keep app idle for long time. After that if we perform any actions related to Monkey cache, we endup with this error.

2. Same issue can be generated in QA automation when we are run our automation scripts.

3. Without any idle time if we try to perform any of the operations related to Monkey Cache, it is working as expected.

**Comment by alex-davies** [comment]
We are noticing a similar error on our app in the wild, although have not reproduced it on a QA environment yet

@jamesmontemagno is there any update in fixing or reproducing this issue? @sykrishna did you find a work around for this issue?
