### ISSUE TITLE
Cached data not persisted between app sessions

### ISSUE THREAD

**Issue by c-lamont** [jamesmontemagno/monkey-cache#60]
I can not confirm this as a bug with MonkeyCache. However I am getting quite a few reports of users having to log in to the app after not using it for 1/2 days.

Users are considered logged in if they have a user token in the cache, and this seems to be missing after a period of the app not being used. The `expireIn` is set to one year.

This happens only on Android and there is no clear device or Android Api level it occurs on.

Has anyone else had this issue or an idea what could be going on? Its impossible to debug.

**Comment by pkhandelwal-cdl** [comment]
The Cache directories where MonkeyCache saves can be cleaned up at any time by the OS. Have you tried changing the base path of where the data is stored? See here https://github.com/jamesmontemagno/monkey-cache#persisting-data-longer

**Comment by jamesmontemagno** [comment]
Yup, it is a cache so it will delete randomly by the system.

**Comment by c-lamont** [comment]
@pkhandelwal-cdl 
Thanks for pointing that out.
Can I add anything as the base path?

**Comment by c-lamont** [comment]
@pkhandelwal-cdl @jamesmontemagno 
I have tried setting the base path but then the access is denied on iOS. I am trying to look for some info on how to resolve this but I can not find anything.
Any ideas on how to get persistent caching working by setting the base path?

**Comment by jamesmontemagno** [comment]
You could use the app directory; https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers?context=xamarin%2Fxamarin-forms&tabs=ios
