### ISSUE TITLE
Clearing Cache While App is Running Causing System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by ArryMatt** [jamesmontemagno/monkey-cache#61]
Steps to reproduce:
1. Run up my app
2. In my Android phone I manually clear the application cache via Settings -> App -> Storage -> Clear Cache
3. Return to my app
4. Go somewhere that uses something cached.
5. The Barrel.Current.Get returns a null, so I go get the data again
6. Barrel.Current.Add then causes the directory not found exception.

The only way I have found around this is to try/catch all of the Add calls and then call Barrel.Create if that Exception occurs.

**Comment by jamesmontemagno** [comment]
Which nuget are you using?

**Comment by ArryMatt** [comment]
1.2.0-beta

I believe the OS deleted the application directory monkey-cache is using when I cleared the cache.  Add and other methods try to access the directory, which is no longer there.

**Comment by jamesmontemagno** [comment]
File system, sqlite, or litedb.

**Comment by ArryMatt** [comment]
Sorry, should have said, file system.
