### ISSUE TITLE
\" added to strings

### ISSUE THREAD

**Issue by ianvink** [jamesmontemagno/monkey-cache#62]
Hi James - Thank you for this wonderful tool.

I upgraded from Beta to version 1.3 (LiteDb). When I request a string, the string now comes back wrapped in \\" . The Beta version returned a string without the \\"

Is there a way to disable that serialization?

     Barrel.Current.Add(key, "dog", expire);
     var x = Barrel.Current.Get<T>(key);   //where T is a string
     // x now is \"dog\"

**Comment by jamesmontemagno** [comment]
Hmmm interesting.... What was your previous beta version?

Can you do 

 var x = Barrel.Current.Get<string>(key);

**Comment by jamesmontemagno** [comment]
is strange because we check if it is a string:

```
			if (BarrelUtils.IsString(result))
			{
				object final = ent.Contents;
				return (T)final;
			}
```

**Comment by jamesmontemagno** [comment]
I just test it here and worked alright....

**Comment by ianvink** [comment]
I was using 1.0.10-Beta

Here it in 1.3:

![image](https://user-images.githubusercontent.com/112916/59521623-9304c700-8e81-11e9-88ae-1c146aa89bf5.png)


Here it is in 1.0.10-Beta, notice the lack of the quote
![image](https://user-images.githubusercontent.com/112916/59521845-18887700-8e82-11e9-8305-aeb3535cbb54.png)

**Comment by jamesmontemagno** [comment]
And what OS is it?

**Comment by ianvink** [comment]
iOS

**Comment by jamesmontemagno** [comment]
Is it encrypted or no?

**Comment by jamesmontemagno** [comment]
Tested on UWP here and it is good.

The only thing I can think is that between those versions we moved from litedb 4.1.2 to 4.1.4, but I doubt that would change it. I really didn't make any huge huge changes, however perhaps you will want to clera the cache and re-add the values? Were these already existing data entries from previous versions?

Here is it running in my iOS simulator:
![image](https://user-images.githubusercontent.com/1676321/59526833-cc8fff00-8e8e-11e9-9b12-c1c40c51e4df.png)

Sample App:
[App31.zip](https://github.com/jamesmontemagno/monkey-cache/files/3291596/App31.zip)

We will figure this out!

**Comment by jamesmontemagno** [comment]
Was never able to reproduce this sorry :(

**Comment by ykoorb** [comment]
Just in case this helps anyone else - I ran into the same sort of problem.

I was adding a `string` into the cache without saying it was a string. When i retrieved it, it was wrapped in quotes.
```CSharp
Barrel.Current.Add(key: key, data: data, expireIn: expireIn);
```

I updated my code to explicitly tell it the type and it was all happy
```CSharp
Barrel.Current.Add<string>(key: key, data: data, expireIn: expireIn);
```
