### ISSUE TITLE
Marking cached data as "modified"

### ISSUE THREAD

**Issue by Robbert-jansen** [jamesmontemagno/monkey-cache#65]
Hi, I have a question.

I was wondering if it's possible the mark cached data as **_modified_**.
Which means that is has to be sent to the server after being modified locally, and not be overwritten with new data from the server.
Does this functionality already exist, I didn't see it in the documentation?

I ask because I'm looking at rewriting my own hamstrung caching implementation, but if this were to have that functionality I'd strongly consider using this instead.

**Comment by jamesmontemagno** [comment]
You could probably mark something in the data object you are caching, but it is just a generic cache on disk. Nothing special.
