### ISSUE TITLE
Data migration

### ISSUE THREAD

**Issue by mr5z** [jamesmontemagno/monkey-cache#66]
Is there any recommended way to handle a previous record of same key but with different type due to update of the code base?
This is like updating your database column into a different type.

```
var val1 = Barrel.Current.Get<TPrevious>(key); // throws
var val2 = Barrel.Current.Get<TUpdated>(key); // OK
```

I'm thinking of something like:

```
Barrel.Current.Configure(config =>
{
    config.ForVersion(2).MigrateType<OldType, NewType>(oldValue =>
    {
         return new NewType
        {
            Id = oldValue.Id,
            // more mapping...
        };
    });
});
```

**Comment by jamesmontemagno** [comment]
There is none currently. You could need to delete the old data and get the new data. Migration isn't something I plan on supporting at all.
