### ISSUE TITLE
Storage of file

### ISSUE THREAD

**Issue by ndastur** [jamesmontemagno/monkey-cache#68]
Sorry to post as an issue. But how (and can) I use MonkeyCache to store files. I guess I can store a base64 string but don't really want the size overhead with that.

**Comment by jamesmontemagno** [comment]
You should just use System.IO https://docs.microsoft.com/en-us/dotnet/standard/io/

**Comment by ndastur** [comment]
Hi @jamesmontemagno .. I should have posted some code. But passing a Stream results in an exception about Timeouts.
```
byte[] media = Convert.FromBase64String(result.data.Media);
Stream stream = new MemoryStream(media);
Barrel.Current.Add<Stream>(item.MediaId, stream, TimeSpan.FromDays(30));
```

**Comment by jamesmontemagno** [comment]
I mean you could... or you could just File.Create https://docs.microsoft.com/en-us/dotnet/api/system.io.file?view=netframework-4.8

Don't use Monkey Cache for this, this it not what you are supposed to do or its purpose. It is for storing simple data. Literally System.IO was created to store files.

**Comment by ndastur** [comment]
ok @jamesmontemagno thanks. I thought it would be a good way to ensure I keep cache clean as I didn't want the media files hanging around forever and didn't want to rely on the OS or user to clean them
