### ISSUE TITLE
currentBarrel.Empty() doesn't delete files with MonkeyCache.FileStore

### ISSUE THREAD

**Issue by virsanna** [jamesmontemagno/monkey-cache#69]
I have detected that the size of app cache doesn't change after emptying the keys - so, the files have not been deleted. I think that it can be connected with file attributes, and can be fixed with  
`File.SetAttributes(destinationFilename, FileAttributes.Normal);  `
before `File.Delete(destinationFilename);`
as it is mentioned here
https://stackoverflow.com/questions/45076903/c-sharp-file-delete-doesnt-not-work

Thanks for the MonkeyCache!

**Comment by jamesmontemagno** [comment]
What platform are you on for testing?

**Comment by virsanna** [comment]
Thanks for the answer! 
Android.

**Comment by jamesmontemagno** [comment]
@Redth thoughts on this? seems like an easy enough fix up.

**Comment by Redth** [comment]
Can’t really hurt to add this in its own try/catch block. I’ll do a PR tomorrow.

**Comment by virsanna** [comment]
@Redth @jamesmontemagno 
Thousand apologies, I have just realized that the error was in my own code. 
Thanks again for the MonkeyCache!
