### ISSUE TITLE
Make UniqueID for NETCore go away

### ISSUE THREAD

**Issue by timheuer** [jamesmontemagno/monkey-cache#8]
By setting the UniqueID for the folder in .NET Core, does the developer have to know that key later?  Can you obfuscate the implementation detail and just create the unique ID folder for me on that platform?  Like just a GUID?

**Comment by jamesmontemagno** [comment]
Yeah, I would like to. The issue is I guess remembering this key for use later. I wanted to use the assembly name of the caller, but it isn't guaranteed to be not null. Thinking about it still.

**Comment by aherrick** [comment]
What is the reason the key needs to be known later? Isn't it simply so when the cache folder is created the folder name doesn't collide?

**Comment by jamesmontemagno** [comment]
The code would just need to be used every time inside the app. So it is persisted in the app. 

The key is there because on Windows the LocalAppDirectory is just... C:\Users\James Montemagno\AppData\Local

So i need to create a unique folder in there.

**Comment by timheuer** [comment]
I need to play around with this more to grok, but does the dev need to set the UniqueID when *reading* the cache as well?

**Comment by jamesmontemagno** [comment]
Nope, you only ever set it once at app startup, which will be the folder that is used and created for life cycle of app. And then just don't change it and it will use the same folder next time.

**Comment by timheuer** [comment]
I see, so a random var x = new GUID() won't work there.  Thinking...

**Comment by jamesmontemagno** [comment]
Yeah, you could just do: Guid.NewGuid().ToString("N")

The probably I have is... how do i remember that so I don't create it again next time?

**Comment by timheuer** [comment]
Okay, looks like you're going with the "always need UniqueId" approach -- honestly that's better than having a plat-specific rule.  Perhaps change to ApplicationId just from an API naming standpoint.

**Comment by jamesmontemagno** [comment]
not sure it matters to much as it doesnt' have to be the app id :)

**Comment by timheuer** [comment]
Your call.  Just speaking from an API design standpoint "UniqueId" is a weird name.  Something like "ApplicationName" or "ApplicatoinId" is more API-friendly naming.  I wasn't suggesting it should be the actual store app name.  

I might give you a UniqueId that isn't folder-name friendly (probably need a test for that)
