### ISSUE TITLE
Can't save FormattedString

### ISSUE THREAD

**Issue by Silver7899** [jamesmontemagno/monkey-cache#89]
I'm sorry if my question is silly. I'm a beginner.

I'm trying to save and extract object. 
Everything works as expected, except for a field of type FormattedString. It remains empty(Spans.Count = 0) when extracted.

What am I doing wrong?

![m1](https://user-images.githubusercontent.com/30808331/91717897-0e43bd00-eb9b-11ea-8b77-0d4c6481f04b.png)

**Comment by jamesmontemagno** [comment]
So, it would have be be completely serialized out via newtonsoft jsonconvert. So perhaps the FormattedText object doesn't support that, which may be true.

So i would try to do this:

```
var json = JsonConvert.SerializeObject(m1);
```

Let me know what that shows.

**Comment by Silver7899** [comment]
I tried and get exception "Newtonsoft.Json.JsonSerializationException: 'Self referencing loop detected for property 'RealParent' with type 'Xamarin.Forms.FormattedString'. Path 'FormattedText.Spans[0]'.'"

After that, I copied the settings from your source code:
`jsonSettings = new JsonSerializerSettings
			{
				ObjectCreationHandling = ObjectCreationHandling.Replace,
				ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
				TypeNameHandling = TypeNameHandling.All,
			};`

And get json:
`{
   "$type":"App1.Message, App1",
   "MessageId":123,
   "Date":"2020-08-31T17:52:20.614719+00:00",
   "FormattedText":{
      "$type":"Xamarin.Forms.FormattedString, Xamarin.Forms.Core",
      "Spans":{
         "$type":"Xamarin.Forms.FormattedString+SpanCollection, Xamarin.Forms.Core",
         "$values":[
            {
               "$type":"Xamarin.Forms.Span, Xamarin.Forms.Core",
               "Style":null,
               "BackgroundColor":{
                  "$type":"Xamarin.Forms.Color, Xamarin.Forms.Core",
                  "IsDefault":true,
                  "A":0.0,
                  "R":0.0,
                  "G":0.0,
                  "B":0.0,
                  "Hue":0.0,
                  "Saturation":0.0,
                  "Luminosity":0.0
               },
               "TextColor":{
                  "$type":"Xamarin.Forms.Color, Xamarin.Forms.Core",
                  "IsDefault":false,
                  "A":1.0,
                  "R":1.0,
                  "G":0.0,
                  "B":0.0,
                  "Hue":1.0,
                  "Saturation":1.0,
                  "Luminosity":0.5
               },
               "CharacterSpacing":0.0,
               "ForegroundColor":{
                  "$type":"Xamarin.Forms.Color, Xamarin.Forms.Core",
                  "IsDefault":false,
                  "A":1.0,
                  "R":1.0,
                  "G":0.0,
                  "B":0.0,
                  "Hue":1.0,
                  "Saturation":1.0,
                  "Luminosity":0.5
               },
               "Text":"Hello",
               "Font":{
                  "$type":"Xamarin.Forms.Font, Xamarin.Forms.Core",
                  "FontFamily":null,
                  "FontSize":0.0,
                  "NamedSize":0,
                  "FontAttributes":0,
                  "IsDefault":true,
                  "UseNamedSize":true
               },
               "FontAttributes":0,
               "FontFamily":null,
               "FontSize":14.0,
               "TextDecorations":0,
               "LineHeight":-1.0,
               "GestureRecognizers":{
                  "$type":"Xamarin.Forms.GestureElement+GestureRecognizerCollection, Xamarin.Forms.Core",
                  "$values":[
                     
                  ]
               },
               "AutomationId":null,
               "ClassId":null,
               "Effects":{
                  "$type":"Xamarin.Forms.TrackableCollection`1[[Xamarin.Forms.Effect, Xamarin.Forms.Core]], Xamarin.Forms.Core",
                  "$values":[
                     
                  ]
               },
               "Id":"1aa8466b-8a6d-4395-86dd-73bbf7a92157",
               "ParentView":null,
               "StyleId":null,
               "LogicalChildren":{
                  "$type":"System.Collections.ObjectModel.ReadOnlyCollection`1[[Xamarin.Forms.Element, Xamarin.Forms.Core]], mscorlib",
                  "$values":[
                     
                  ]
               },
               "EffectControlProvider":null,
               "Platform":null,
               "Dispatcher":{
                  "$type":"Xamarin.Forms.FallbackDispatcher, Xamarin.Forms.Core",
                  "IsInvokeRequired":false
               },
               "BindingContext":null
            },
            {
               "$type":"Xamarin.Forms.Span, Xamarin.Forms.Core",
               "Style":null,
               "BackgroundColor":{
                  "$type":"Xamarin.Forms.Color, Xamarin.Forms.Core",
                  "IsDefault":true,
                  "A":0.0,
                  "R":0.0,
                  "G":0.0,
                  "B":0.0,
                  "Hue":0.0,
                  "Saturation":0.0,
                  "Luminosity":0.0
               },
               "TextColor":{
                  "$type":"Xamarin.Forms.Color, Xamarin.Forms.Core",
                  "IsDefault":false,
                  "A":1.0,
                  "R":0.0,
                  "G":0.0,
                  "B":1.0,
                  "Hue":0.66666668653488159,
                  "Saturation":1.0,
                  "Luminosity":0.5
               },
               "CharacterSpacing":0.0,
               "ForegroundColor":{
                  "$type":"Xamarin.Forms.Color, Xamarin.Forms.Core",
                  "IsDefault":false,
                  "A":1.0,
                  "R":0.0,
                  "G":0.0,
                  "B":1.0,
                  "Hue":0.66666668653488159,
                  "Saturation":1.0,
                  "Luminosity":0.5
               },
               "Text":"World",
               "Font":{
                  "$type":"Xamarin.Forms.Font, Xamarin.Forms.Core",
                  "FontFamily":null,
                  "FontSize":0.0,
                  "NamedSize":0,
                  "FontAttributes":0,
                  "IsDefault":true,
                  "UseNamedSize":true
               },
               "FontAttributes":0,
               "FontFamily":null,
               "FontSize":14.0,
               "TextDecorations":0,
               "LineHeight":-1.0,
               "GestureRecognizers":{
                  "$type":"Xamarin.Forms.GestureElement+GestureRecognizerCollection, Xamarin.Forms.Core",
                  "$values":[
                     
                  ]
               },
               "AutomationId":null,
               "ClassId":null,
               "Effects":{
                  "$type":"Xamarin.Forms.TrackableCollection`1[[Xamarin.Forms.Effect, Xamarin.Forms.Core]], Xamarin.Forms.Core",
                  "$values":[
                     
                  ]
               },
               "Id":"22e62d8d-b202-4e4c-94be-677ab1d41881",
               "ParentView":null,
               "StyleId":null,
               "LogicalChildren":{
                  "$type":"System.Collections.ObjectModel.ReadOnlyCollection`1[[Xamarin.Forms.Element, Xamarin.Forms.Core]], mscorlib",
                  "$values":[
                     
                  ]
               },
               "EffectControlProvider":null,
               "Platform":null,
               "Dispatcher":{
                  "$type":"Xamarin.Forms.FallbackDispatcher, Xamarin.Forms.Core",
                  "IsInvokeRequired":false
               },
               "BindingContext":null
            }
         ]
      },
      "AutomationId":null,
      "ClassId":null,
      "Effects":{
         "$type":"Xamarin.Forms.TrackableCollection`1[[Xamarin.Forms.Effect, Xamarin.Forms.Core]], Xamarin.Forms.Core",
         "$values":[
            
         ]
      },
      "Id":"56b26e47-5fd0-41fa-9d8e-716c5a1a71da",
      "ParentView":null,
      "StyleId":null,
      "LogicalChildren":{
         "$type":"System.Collections.ObjectModel.ReadOnlyCollection`1[[Xamarin.Forms.Element, Xamarin.Forms.Core]], mscorlib",
         "$values":[
            
         ]
      },
      "RealParent":null,
      "Parent":null,
      "EffectControlProvider":null,
      "Platform":null,
      "Dispatcher":{
         "$type":"Xamarin.Forms.FallbackDispatcher, Xamarin.Forms.Core",
         "IsInvokeRequired":false
      },
      "BindingContext":null
   }
}`

Looks like the object is saved correctly.

After after that I tried
`var result = JsonConvert.DeserializeObject<Message>(json, jsonSettings);` and got the same result as in the first post.

I also tried to set ObjectCreationHandling.Auto and got the desired result.

I googled information about this setting but couldn't understand when which mode I should use. Could you explain why you use ObjectCreationHandling.Replace?

**Comment by jamesmontemagno** [comment]
You can pass in jsonsettings when you call `Add` or `Get`, which should fix it if you want to use Auto.

Not sure why I use Replace. Idk.

**Comment by Silver7899** [comment]
James! Thank you for all your work. You're making this world a better place. I wish you endless happiness.
