### ISSUE TITLE
Question: How to move monkey file cache from app cache directory to app storage directory.

### ISSUE THREAD

**Issue by JMan7777** [jamesmontemagno/monkey-cache#93]
Hi,

I'm using the monkey file cache in my app and by default it uses the app cache directory to keep its internal file. This is now creating me some issues. Is there an easy way to move the existing file cache to the app storage (I don't want my users to loose there cache content)?
Do I just need to move the cache file on file level or can I do it somehow inside my code direct with monkey cache functionality?

Thx a lot.

**Comment by jamesmontemagno** [comment]
You can change where the data is stored via: https://github.com/jamesmontemagno/monkey-cache#persisting-data-longer you could technically move the file yourself to not lose data. Although it is a cache... not a database so ideally you should feel fine with losing all of the data at anytime.
